version: '#{build}'
platform: x64
environment:
  QT_BASE_X64: C:\Qt\5.8\msvc2015_64
  PYTHON3_BASE_X64: C:\Miniconda36-x64
install:
- cmd: C:\Miniconda36-x64\Scripts\conda install numpy -y
build:
  project: NionUILauncher.vcxproj
  verbosity: minimal
artifacts:
- path: x64\Debug\
  name: NionUILauncher-Windows
deploy:
  provider: GitHub
  auth_token:
    secure: "JOsBeG4/+uADDmapGTFqxFVqxB6MAN6TdJmamNvc4OFw96ifhEaSzOUbVbRcRLI9"
  artifact: /NionUILauncher-Windows.zip/
  draft: false
  prerelease: false
  tag: $(appveyor_repo_tag_name)
  on:
    appveyor_repo_tag: true
